name:                hs-specks
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hs-specks#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - random
  - matrix
  - vector

executables:
  hs-specks:
    source-dirs:      src
    main:             Main.hs
